### ISSUE TITLE
Rails set to false using .rambo.yml

### ISSUE THREAD

**Issue by danascheider** [danascheider/rambo#67]
## Summary

When using the Rake task with a `.rambo.yml` config file, Rails is set to false even when the .rambo.yml file contains `rails: true`.

## Expected Behavior

The Rails syntax should be used by default unless the `.rambo.yml` file specifies `rails: false`.

## Current Behavior

With the following `.rambo.yml` file content:
```yaml
raml: doc/raml/repaymnt_estimatr.raml
rails: true
```
The following errors are raised in CI (which runs the Rake task):
```
NameError:
  undefined local variable or method `last_response' for #<RSpec::ExampleGroups::RepaymntEstimatr::Estimate::POST:0x00000002ca5fd8>
# ./spec/contract/repaymnt_estimatr_spec.rb:39:in `block (5 levels) in <top (required)>'
# ./spec/contract/repaymnt_estimatr_spec.rb:39:in `open'
# ./spec/contract/repaymnt_estimatr_spec.rb:39:in `block (4 levels) in <top (required)>'
```

## Possible Solution

Check that the entry point to Rambo through the Rake task sets the correct default options (including both the correct Rails option and the correct location of the RAML doc. Additionally, check that the correct options are set when reading the `.rambo.yml` file.

## Context

I added the Rambo rake task to my `.travis.yml` file to be run before RSpec in CI. Initially, Rambo couldn't find the `repaymnt_estimatr.raml` file in what is supposed to be the default location, so I created a `.rambo.yml` file specifying the location. However, when it ran in CI, the generated tests used the non-Rails syntax for Rack::Test, causing failures in CI.

## Your Environment

* Version used: 0.2.0
* Rails version 4.0.13
* Travis CI
* Using the Rambo Rake task
* `.rambo.yml` in root directory (see contents above)

**Comment by danascheider** [comment]
This problem is no longer occurring in version 0.5.
