### ISSUE TITLE
Rails 5/RSpec 3.5 tests failing due to JSON being sent instead of PORO

### ISSUE THREAD

**Issue by danascheider** [danascheider/rambo#81]
## Summary

I am building a demo app using Rails 5 and RSpec 3.5. When I run the generated contract tests, I'm getting an error indicating the required `:data` key is missing from the `params` hash. Further investigation determined this was because the endpoint was expecting a PORO and got a JSON object. I need to investigate whether this is caused by the particular version of RSpec, the particular version of Rails, or some other reason (that didn't get in the way of Repaymnt Estimatr tests working).

## Expected Behavior

After running Rambo, assuming the API is functioning as documented, the tests should pass.

## Current Behavior

When running the generated RSpec tests for my Rails 5 app, the tests raised this error:
```
Failures:

  1) Personal Calculator /age POST calculate age given a birthdate
     Failure/Error: params.require(:data).permit(:first_name, :last_name, :birthdate)

     ActionController::ParameterMissing:
       param is missing or the value is empty: data
     # ./app/controllers/calculations_controller.rb:26:in `profile_params'
     # ./app/controllers/calculations_controller.rb:17:in `resp_body'
     # ./app/controllers/calculations_controller.rb:5:in `age'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/dana/.rvm/gems/ruby-2.3.1@personal_calculator/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # ./spec/contract/personal_calculator_spec.rb:36:in `block (4 levels) in <top (required)>'
```
The cause proved to be that Rack middleware is not running when the server processes the Rack::Test request, and as a result, the JSON object is passed through to the controller as-is, instead of being parsed.

## Possible Solution

Since the solution will depend heavily on what the cause turns out to be, I will update this issue as I learn more.

The first thing I learned is that the behavior is the same with Rails 4. Since Rambo doesn't support RSpec 2, the problem also can't be with RSpec 3.

## Steps to Reproduce (for bugs)

1. Create a working Rails 4 or 5 API with RAML
2. Install RSpec v. 3.5 and Rambo
3. Run `rake rambo`
4. Run `bundle exec rspec spec/contract`
5. See errors

## Your Environment

* Version used: 0.4
* RSpec-Rails: 3.5.1
* Rails: 5.0.0
* Rack::Test: 0.6.3

**Comment by danascheider** [comment]
I'm going to create a new release that fixes this. @zeisler and @mleglise-renew, please let me know if version 0.5 breaks Repaymnt Estimatr.
