### ISSUE TITLE
include parsed as string

### ISSUE THREAD

**Issue by splitice** [danascheider/rambo#92]
## Summary

With Raml files including other RAML files (such as for re-use of sections) the included file is treated as a YAML string

## Expected Behavior

Correct operation

## Current Behavior
```
C:\Users\splitice\Documents\GitHub\hub_api>rambo docs/api_v1.raml
    ____   ___     __  ___ ____   ____
   / __ \ /   |   /  |/  // __ ) / __ \
  / /_/ // /| |  / /|_/ // __  |/ / / /
 / _, _// ___ | / /  / // /_/ // /_/ /
/_/ |_|/_/  |_|/_/  /_//_____/ \____/

Error: undefined method `each' for #<String:0x00000000036ee8f0>
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/method.rb:68:in `parse_bodies'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/method.rb:48:in `block in parse_attributes'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/method.rb:39:in `each'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/method.rb:39:in `parse_attributes'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/method.rb:31:in `parse'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/resource.rb:43:in `block in parse_attributes'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/resource.rb:37:in `each'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/resource.rb:37:in `parse_attributes'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/resource.rb:30:in `parse'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/root.rb:43:in `block in parse_attributes'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/root.rb:31:in `each'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/root.rb:31:in `parse_attributes'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser/root.rb:24:in `parse'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser.rb:20:in `parse'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser.rb:28:in `parse_file'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/raml-rb-1.2.0/lib/raml/parser.rb:39:in `parse_file'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rambo_ruby-0.7.1/lib/rambo/document_generator.rb:25:in `initialize'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rambo_ruby-0.7.1/lib/rambo/document_generator.rb:13:in `new'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rambo_ruby-0.7.1/lib/rambo/document_generator.rb:13:in `generate!'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rambo_ruby-0.7.1/lib/rambo.rb:15:in `generate_contract_tests!'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rambo_ruby-0.7.1/lib/cli.rb:19:in `run!'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rambo_ruby-0.7.1/bin/rambo:26:in `<top (required)>'
        C:/Ruby24-x64/bin/rambo:23:in `load'
        C:/Ruby24-x64/bin/rambo:23:in `<main>'
```

A puts dump shows that the contents of the string is unparsed yaml
## Your Environment

* Version used: Latest gem
* Operating System and version: Windows

**Comment by splitice** [comment]
Suggested fix:

```
module Raml
  class Parser

    def initialize
      Psych.add_domain_type 'include', 'include' do |_, value|
        raw = File.read(value)
        YAML.load(raw)
      end
    end
```

**Comment by splitice** [comment]
Oops Should be raised against raml-rb.
